# documentation: https://hub.docker.com/r/ruimarinho/bitcoin-core/
# slogan: A self-hosted Bitcoin Core full node.
# tags: cryptocurrency,node,blockchain,bitcoin
# logo: svgs/bitcoin.svg

services:
  bitcoin-core:
    image: 'ruimarinho/bitcoin-core:latest'
    environment:
      - 'BITCOIN_RPCUSER=${BITCOIN_RPCUSER:-bitcoinuser}'
      - 'BITCOIN_RPCPASSWORD=${SERVICE_PASSWORD_PASSWORD64}'
      - 'BITCOIN_PRINTTOCONSOLE=${BITCOIN_PRINTTOCONSOLE:-1}'
      - 'BITCOIN_TXINDEX=${BITCOIN_TXINDEX:-1}'
      - 'BITCOIN_SERVER=1'
    volumes:
      - '/mnt/blockchain_data:/home/bitcoin/.bitcoin' # here use your own path, where you want to store the blockchain data
    network_mode: "host" # use host network for secure connection only through localhost
    command:
      [
        "-datadir=/home/bitcoin/.bitcoin",
        "-rpcbind=127.0.0.1", # only allow local connections
        "-rpcallowip=127.0.0.1",
        "-rpcuser=${BITCOIN_RPCUSER}",
        "-rpcpassword=${SERVICE_PASSWORD_PASSWORD64}",
        "-printtoconsole=${BITCOIN_PRINTTOCONSOLE}",
        "-txindex=${BITCOIN_TXINDEX}",
        "-server=${BITCOIN_SERVER}"
      ]
