services:
  cyberchef:
    image: 'ghcr.io/gchq/cyberchef:latest'
    environment:
      - SERVICE_FQDN_CYBERCHEF_80
    volumes:
      - 'cyberchef-data:/app/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 30s
      timeout: 10s
      retries: 3
