# documentation: https://docs.flowiseai.com/
# slogan: Flowise is an open source low-code tool for developers to build customized LLM orchestration flows & AI agents.
# tags: lowcode, nocode, ai, llm, openai, anthropic, machine-learning, rag, agents, chatbot, api, team, bot, flows
# logo: svgs/flowise.png
# port: 3001

services:
  flowise:
    image: flowiseai/flowise
    restart: always
    environment:
      - SERVICE_FQDN_FLOWISE_3001
      - DEBUG=false
      - DISABLE_FLOWISE_TELEMETRY=true
      - PORT=3001
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_PATH=/root/.flowise/logs
      - BLOB_STORAGE_PATH=/root/.flowise/storage
      - FLOWISE_USERNAME=${SERVICE_USER_FLOWISE}
      - FLOWISE_PASSWORD=${SERVICE_PASSWORD_FLOWISE}
    volumes:
      - flowise_data:/root/.flowise
    healthcheck:
      test:
        - CMD-SHELL
        - wget
        - --no-verbose
        - --tries=1
        - --spide
        - http://localhost:3001
      interval: 5s
      timeout: 5s
      retries: 3
