# documentation: https://docs.hoarder.app/
# slogan: an open source "Bookmark Everything" app that uses AI for automatically tagging the content you throw at it.
# tags: media,read-it-later,pocket-alternative,omnivore-alternative,instapaper-alternative
# logo: svgs/hoarder.svg
# port: 3000

services:
  web:
    image: 'ghcr.io/hoarder-app/hoarder:release'
    restart: unless-stopped
    volumes:
      - 'data:/data'
    environment:
      - SERVICE_FQDN_HOARDER
      - NEXTAUTH_SECRET=${SERVICE_PASSWORD_HOARDERNEXTAUTH}
      - MEILI_MASTER_KEY=${SERVICE_PASSWORD_MEILI}
      - NEXTAUTH_URL=${SERVICE_FQDN_HOARDER}
      - MEILI_ADDR=http://meilisearch:7700
      - BROWSER_WEB_URL=http://chrome:9222
      - DATA_DIR=/data
  chrome:
    image: 'gcr.io/zenika-hub/alpine-chrome:124'
    restart: unless-stopped
    command:
      - '--no-sandbox'
      - '--disable-gpu'
      - '--disable-dev-shm-usage'
      - '--remote-debugging-address=0.0.0.0'
      - '--remote-debugging-port=9222'
      - '--hide-scrollbars'
  meilisearch:
    image: 'getmeili/meilisearch:v1.6'
    restart: unless-stopped
    environment:
      - MEILI_NO_ANALYTICS=true
      - NEXTAUTH_SECRET=${SERVICE_PASSWORD_HOARDERNEXTAUTH}
      - MEILI_MASTER_KEY=${SERVICE_PASSWORD_MEILI}
      - NEXTAUTH_URL=${SERVICE_FQDN_HOARDER}
    volumes:
      - 'meilisearch:/meili_data'
