services:
  jupyter-notebook:
    image: 'quay.io/jupyter/base-notebook:latest'
    environment:
      - SERVICE_FQDN_JUPYTER_8888
    volumes:
      - '/jupyter:/home/jovyan/work'
    command: start-notebook.sh
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8888/"]
      interval: 30s
      timeout: 20s
      retries: 10
