# documentation: https://docs.organizr.app/
# slogan: Homelab Services Organizer
# tags: tool
# logo: svgs/organizr.png
# port: 80

services:
  organizr:
    image: organizr/organizr:latest
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_ORGANIZR_80
      - branch=v2-master
    volumes:
      - organizr-data:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 2s
      timeout: 10s
      retries: 30
