# documentation: https://owncloud.com/docs
# slogan: ownCloud with Open Web UI integrates file management with a powerful, user-friendly interface.
# tags: owncloud,file-management,open-web-ui,integration,cloud
# logo: svgs/owncloud.svg
# port: 8080

version: "3.9"
services:
  owncloud:
    image: "owncloud/server:latest"
    container_name: owncloud_server
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    environment:
      - SERVICE_FQDN_OWNCLOUD_8080
      - "OWNCLOUD_DOMAIN=127.0.0.1:8080"
      - "OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS:-localhost,127.0.0.1}"
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - "OWNCLOUD_DB_PASSWORD=owncloud"
      - OWNCLOUD_DB_HOST=mariadb
      - "OWNCLOUD_ADMIN_USERNAME=${ADMIN_USER:-owncloud}"
      - "OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD:-owncloud}"
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test:
        - CMD
        - /usr/bin/healthcheck
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "files:/mnt/data"
    ports:
      - "8080:8080"

  mariadb:
    image: "mariadb:latest"
    container_name: owncloud_mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - TZ=auto
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
      - "--max-allowed-packet=128M"
      - "--innodb-log-file-size=64M"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"

  redis:
    image: "redis:6"
    container_name: owncloud_redis
    restart: unless-stopped
    command:
      - "--databases"
      - "1"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"

volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local
