# documentation: https://github.com/plexinc/pms-docker
# slogan: Plex combines free movies & TV with the best free streaming services, so there’s always more to discover.
# tags: media, server, movies, tv, music
# logo: svgs/plex.svg
# port: 32400

services:
  plex:
    image: plexinc/pms-docker:latest
    environment:
      - SERVICE_FQDN_PLEX_32400
      - _APP_URL=$SERVICE_FQDN_PLEX
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Toronto}
      - PLEX_CLAIM=${PLEX_CLAIM}
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - plex-config:/config
      - plex-tvshows:/data/tvshows
      - plex-movies:/data/movies
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/identity"]
      interval: 2s
      timeout: 10s
      retries: 15
